name: Mark stale issues and pull requests
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    name: Mark stale issues and pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity.'
          close-issue-message: 'This issue was closed because it has been stale for 7 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stale for 7 days with no activity.'
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: 'pinned,security'
          exempt-pr-labels: 'pinned,security'